source 'https://rubygems.org'

gem 'rails', '~> 4.0'
gem 'actionpack-action_caching'
gem 'debugger'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'jbuilder', '~> 1.2'

gem 'mongoid', '~> 4.0'
gem 'will_paginate_mongoid'
gem 'forma', '~>0.1'
gem 'bootstrap-will_paginate'
gem 'ka'

gem 'libxml-ruby'
gem 'rubyzip'

gem 'prawn'
gem 'prawn_rails'
gem 'axlsx_rails'
gem 'roo'
gem 'geokit'
gem 'geoutm'

gem 'shortest-path', path: '../shortest-path'
gem 'rmagick'
gem 'resque'